# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)
Denise Wafa B. Españo | 2ECE-D
<div style="border-bottom: 2px solid gray; margin-bottom: 10px;"></div>

## A. REPRODUCIBLE NORMALIZATION PROBLEM

In [27]:
import numpy as np

In [34]:
np.random.seed(2112)
X = np.random.randint (10, 101, size=(5,5))
print(X)

[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [41]:
mean = np.mean(X)
std = np.std(X)
X_normalized = (X - mean / std)
X_normalized

array([[46.2075524,  9.2075524, 13.2075524, 65.2075524, 19.2075524],
       [ 9.2075524, 39.2075524, 11.2075524, 64.2075524, 22.2075524],
       [69.2075524, 77.2075524, 51.2075524, 65.2075524, 68.2075524],
       [75.2075524, 33.2075524, 89.2075524, 17.2075524, 94.2075524],
       [33.2075524, 52.2075524, 35.2075524, 39.2075524, 15.2075524]])

In [43]:
print("Mean of X:", mean)
print("Std of x:",std)


Mean of X: 46.36
Std of x: 25.864075471588002


In [44]:
np.save('x_normalized.npy', X_normalized)

## B. Cubes Divisible by 4 Problem

In [51]:
C = (np.arange(1,101) ** 3).reshape(10,10)
div_by_4 = C[C % 4 == 0]

In [55]:
print("Shape of C:", C.shape)
print("\nArray div_by_4:\n", div_by_4)
print("\nNumber of selected elements:", div_by_4.size)


Shape of C: (10, 10)

Array div_by_4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of selected elements: 50


In [56]:
np.save('div_by_4.npy', div_by_4)

## C. Above-Mean Sqaures Problem

In [63]:
S = (np.arange(1,37) ** 2).reshape(6,6)
S_mean = np.mean(S)
above_mean = S[S > S_mean]

In [67]:
print("Array S:\n", S)
print("\nS_mean:", S_mean)
print("\nArray above_mean:\n", above_mean)
print("\nNumber of selected elements:", above_mean.size)


Array S:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

S_mean: 450.1666666666667

Array above_mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15


In [70]:
np.save('above_mean.npy', above_mean)